# Importaciones

In [1]:
import numpy as np
import pandas as pd
import math

# Paso Nº1:

Suponemos que tenemos un grupo de decisión con miembros K. La calificación difusa del k-ésimo tomador de decisiones sobre la alternativa $A_{i}$ con respecto a el criterio $C_{j}$ se denota $\tilde{x}_{ij}^{k}$ = $(a_{ij}^{k}, b_{ij}^{k},c_{ij}^{k})$ y el peso del criterio $C_{j}$ se remarca como $\tilde{w}_{j}^{k}$ = $(w_{j1}^{k}, w_{j2}^{k},w_{j3}^{k})$

In [2]:
def paso1(matrix):
    
    rows, columns = matrix.shape
    
    fuzzy_matrix = np.zeros((rows,columns), dtype = np.ndarray)
    
    for i in range(rows):
        for j in range(columns):
            if(matrix[i,j] < 10.0):
                fuzzy_matrix[i,j] = np.array([0.0, 0.0, 1.0])
                
            elif(matrix[i,j] >= 10.0 and matrix[i,j] < 20.0):
                fuzzy_matrix[i,j] =np.array([0.0, 1.0, 3.0])
                
            elif(matrix[i,j] >= 20.0 and matrix[i,j] < 40.0):
                fuzzy_matrix[i,j] = np.array([1.0, 3.0, 5.0])
                
            elif(matrix[i,j] >= 40.0 and matrix[i,j] < 55.0):
                fuzzy_matrix[i,j] = np.array([3.0, 5.0, 7.0])
                
            elif(matrix[i,j] >= 55.0 and matrix[i,j] < 70.0):
                fuzzy_matrix[i,j] = np.array([5.0, 7.0, 9.0])
            
            elif(matrix[i,j] >= 70.0 and matrix[i,j] < 100.0):
                fuzzy_matrix[i,j] = np.array([7.0, 9.0, 10.0])
            
            elif(matrix[i,j] == 100.0):
                fuzzy_matrix[i,j] = np.array([9.0, 10.0, 10.0])
                
    return fuzzy_matrix

# Paso Nº2

Calcule las calificaciones difusas agregadas para las alternativas y los pesos difusos agregados para los criterios.
    
La calificación difusa agregada $x_{ij} = (a_{ij}, b_{ij}, c_{ij})$ de la i-ésima alternativa con respecto a el j-ésimo criterio se obtiene de la siguiente manera:
    

$ a_{ij} = \min_{k}\left\{a_{i j}^{k}\right\}, b_{i j}=\frac{1}{K} \sum_{k=1}^{K} b_{i j}^{k}, c_{i j}=\max _{k}\left\{c_{i j}^{k}\right\}$

El peso difuso agregado $w_{j} = (w_{j1}, w_{j2}, w_{j3}$ para el criterio $C_{j}$ se calcula como:
    
$w_{j 1}=\min _{k}\left\{w_{j 1}^{k}\right\}, w_{j 2}=\frac{1}{K} \sum_{k=1}^{K} w_{j 2}^{k}, w_{j 3}=\max _{k}\left\{w_{j 3}^{k}\right\}$

donde k es el k-ésimo decisor del problema


En esta situación al tener solo un decisor en el problema el paso se obviara.


# Paso Nº3

Calcule la matriz de decisión difusa normalizada
    
La matriz de decisión difusa normalizada es $\tilde{R} = [\tilde{r}_{ij}]$, donde
    
    
$\tilde{r}_{i j}=\left(\frac{a_{i j}}{c_{j}^{*}}, \frac{b_{i j}}{c_{j}^{*}}, \frac{c_{i j}}{c_{j}^{*}}\right) \text{ de donde } c_{j}^{*}=\max _{i}\left\{c_{i j}\right\} \text{Criterios de beneficio}$

    
$ \tilde{r}_{i j}=\left(\frac{c_{j}^{-}}{c_{i j}}, \frac{c_{j}^{-}}{b_{i j}}, \frac{c_{j}^{-}}{a_{ij}}\right) \text { de donde } c_{j}^{-}=\min _{i}\left\{a_{ij}\right\} \text {Criterios de costo} .
$

In [11]:
def paso3(matrix, criteria):
    
    rows, columns = matrix.shape
    
    fuzzy_normalized = np.copy(matrix) 
    
    benefit_criteria = np.zeros(columns, dtype = np.ndarray)
    
    cost_criteria = np.zeros(columns, dtype = np.ndarray)
    
    maximize = 0
    minimize = 100
    
    benefit_number = np.array([0,0,0])
    cost_number = np.array([0,0,0])
    
    for j in range(columns):
        for i in range(rows):
            if(matrix[i,j][2] > maximize):
                benefit_number = matrix[i,j]
                maximize = matrix[i,j][2]
            if(minimize > matrix[i,j][0]):
                cost_number = matrix[i,j]
                minimize = matrix[i,j][0]
        
        benefit_criteria[j] = benefit_number
        cost_criteria[j] = cost_number
        
        maximize = 0
        minimize = 100
        
    for i in range(rows):
        for j in range(columns):
            if(criteria[j]):
                fuzzy_normalized[i,j][0] = matrix[i,j][0]/benefit_criteria[j][2]
                fuzzy_normalized[i,j][1] = matrix[i,j][1]/benefit_criteria[j][2]
                fuzzy_normalized[i,j][2] = matrix[i,j][2]/benefit_criteria[j][2]
                
            else:
                fuzzy_normalized[i,j][0] = cost_criteria[j][0]/matrix[i,j][2]
                fuzzy_normalized[i,j][1] = cost_criteria[j][0]/matrix[i,j][1]
                fuzzy_normalized[i,j][2] = cost_criteria[j][0]/matrix[i,j][0]
                
    return fuzzy_normalized  
    


# Paso Nº4 

Calcular la matriz de decisión difusa normalizada ponderada.
    
$\tilde{V} = (\tilde{v}_{ij}), \text{ donde } \tilde{v}_{ij} = \tilde{r}_{ij} \times w_{j}$

    
    

In [3]:
def paso4(matrix, weights):
    
    rows, columns = matrix.shape
    
    fuzzy_weighted = np.copy(matrix)
    
    for i in range(rows):
        for j in range(columns):
            fuzzy_weighted[i,j] = matrix[i,j]*weights[j]

            
    return fuzzy_weighted

# Paso 5 

 Calcular la solución ideal positiva disusa y la solución ideal negativa difusa, calculadas de la siguiente manera respectivamente:

$ A^{*} = (\tilde{v}_{1}^{*}, \tilde{v}_{2}^{*}, \ldots, \tilde{v}_{n}^{*}) \text{ donde } \tilde{v}_{j}^{*} = \max_{i}\{v_{ij3}\}$

$ A^{-} = (\tilde{v}_{1}^{-}, \tilde{v}_{2}^{-}, \ldots, \tilde{v}_{n}^{-}) \text{ donde } \tilde{v}_{j}^{-} = \min_{i}\{v_{ij1}\}$

In [4]:
def paso5(matrix):
    
    rows, columns = matrix.shape
    
    positive_ideal_solution = np.zeros(columns, dtype = np.ndarray)
    negative_ideal_solution = np.zeros(columns, dtype =  np.ndarray)
    
    
    fuzzy_max = np.array([0,0,0])
    fuzzy_min = np.array([1000,1000,1000])
   
    for j in range(columns):
        for i in range(rows):
            
            if(matrix[i,j][2] > fuzzy_max[2]):
                fuzzy_max = matrix[i,j]
                
            elif(matrix[i,j][2] == fuzzy_max[2]):
                if(matrix[i,j][1] > fuzzy_max[1]):
                    fuzzy_max = matrix[i,j]
                
             
            if(matrix[i,j][0] < fuzzy_min[0]):
                fuzzy_min = matrix[i,j]
                
            elif(matrix[i,j][0] == fuzzy_min[0]):
                if(matrix[i,j][1] < fuzzy_min[1]):
                    fuzzy_min = matrix[i,j]

                
                
        positive_ideal_solution[j] = fuzzy_max
        negative_ideal_solution[j] = fuzzy_min
        fuzzy_max = np.array([0,0,0])
        fuzzy_min = np.array([1000,1000,1000])
        
    return positive_ideal_solution, negative_ideal_solution
        

# Paso Nº6

Calcule la distancia de cada alternativa a la solución ideal positiva y negativa, usando (2)
    
$d_{i}^{*}=\sum_{j=1}^{n} d\left(\tilde{v}_{i j}, \tilde{v}_{j}^{*}\right), d_{i}^{-}=\sum_{j=1}^{n} d\left(\tilde{v}_{i j}, \tilde{v}_{j}^{-}\right)$

donde

$d(\tilde{x}, \tilde{y}):=\sqrt{\frac{1}{3}\left[\left(a_{1}-a_{2}\right)^{2}+\left(b_{1}-b_{2}\right)^{2}+\left(c_{1}-c_{2}\right)^{2}\right]}$

In [5]:
def paso6(matrix, positive_ideal_solution, negative_ideal_solution):
    
    rows, columns = matrix.shape
    
    positive_distance = []
    negative_distance = []
    acum1 = 0
    acum2 = 0
    
    for i in range(rows):
        for j in range(columns):
            acum1 = acum1 + fuzzy_distance(matrix[i,j],positive_ideal_solution[j])
        
            
            acum2 = acum2 + fuzzy_distance(matrix[i,j], negative_ideal_solution[j])
        
        
        positive_distance.append(acum1)
        negative_distance.append(acum2)
        acum1 = 0
        acum2 = 0
    
        
    return positive_distance, negative_distance
         

In [6]:
def fuzzy_distance(p1,p2):
    
    inner = (np.linalg.norm(p1-p2))**2
    
    distancia = ((1/3)*inner)**(1/2)
    
    return distancia 

# Paso Nº7

Estimar el coeficiente de cercanía $(CC_{i})$ para cada alternativa
    
$CC_{i}=\frac{d_{i}^{-}}{d_{i}^{-}+d_{i}^{*}}$


In [7]:
def paso7(positive_distance, negative_distance):
    n = positive_distance.size
    
    cc = np.zeros(n, dtype = float)
        
    for i in range(n):
        cc[i] = negative_distance[i]/(negative_distance[i] + positive_distance[i])
        
    return cc

# Paso Nº8 

Clasificar las alternativas, aquella con coeficiente de cercanía más alto representa la mejor alternativa

In [8]:
def ranking(data):
    return [i+1 for i in data.argsort()]

In [12]:
matrix = np.array([
    [70.0 ,40.0 ,70.0 ,25.0, 50.0, 80.0, 100.0, 70.0, 70.0, 50.0],
    [60.0 ,55.0 ,50.0 ,45.0, 50.0, 70.0, 100.0, 80.0, 80.0, 60.0],
    [50.0 ,70.0 ,50.0 ,60.0, 60.0, 70.0, 100.0, 70.0, 30.0, 30.0],
    [80.0 ,90.0 ,20.0 ,30.0, 70.0, 100.0, 100.0, 80.0, 50.0, 40.0]])

fuzzy_weights = np.array([[3,5,7],[3,5,7],[3,5,7],[3,5,7],[3,5,7],[3,5,7],[3,5,7],[3,5,7],[3,5,7],[3,5,7]])

#Maximizar - True 
#Minimizar - False

criteria = np.array([True, True, True, True, True, True ,True, True, True, False])

fuzzy_matrix = paso1(matrix)

normalized_fuzzy_matrix = paso3(fuzzy_matrix, criteria)

weighted_fuzzy_matrix = paso4(normalized_fuzzy_matrix,fuzzy_weights)

positive_ideal_solution, negative_ideal_solution = paso5(weighted_fuzzy_matrix)

positive_distance, negative_distance = paso6(weighted_fuzzy_matrix, positive_ideal_solution, negative_ideal_solution)

cc = paso7(np.array(positive_distance), np.array(negative_distance))

rankings = ranking(cc)


In [13]:
print("Results:")

print("Positive distance ", positive_distance)
print("Negative distance ", negative_distance)

print("--------------------------------------------------------------------")

print("Positive ideal solution ", positive_ideal_solution)
print("Negative ideal solution ", negative_ideal_solution)

print("--------------------------------------------------------------------")

print("Closeness coefficient ",cc)
print("Rankings ", rankings)

print("--------------------------------------------------------------------")


Results:
Positive distance  [330.8886250528091, 77.9899531805609, 146.32410808400408, 36.72941209011067]
Negative distance  [0.5025107031723017, 255.78532700935503, 237.3176814991281, 295.48057055437476]
--------------------------------------------------------------------
Positive ideal solution  [array([21., 45., 70.]) array([21., 45., 70.]) array([ 9., 25., 49.])
 array([ 3., 15., 35.]) array([2.1, 4.5, 7. ]) array([27., 50., 70.])
 array([27., 50., 70.]) array([21., 45., 70.]) array([21., 45., 70.])
 array([ 0.33333333,  0.71428571, 63.        ])]
Negative ideal solution  [array([2.1, 4.5, 7. ]) array([0.9, 2.5, 4.9]) array([2.1, 4.5, 7. ])
 array([0.33333333, 1.66666667, 3.88888889]) array([0.9, 2.5, 4.9])
 array([2.1, 4.5, 7. ]) array([2.7, 5. , 7. ]) array([2.1, 4.5, 7. ])
 array([2.1, 4.5, 7. ]) array([ 0.08571429,  0.2       , 49.        ])]
--------------------------------------------------------------------
Closeness coefficient  [0.00151637 0.76633994 0.61859184 0.88943917]


In [16]:
temp =  negative_ideal_solution
df = pd.DataFrame(temp).T
df.to_excel("matrix1.xlsx")

In [19]:
temp3 = np.transpose(weighted_fuzzy_matrix)
df = pd.DataFrame(temp3).T
df.to_excel("eigthed_fuzzy_matrix.xlsx")